<?php
	require('sidebar.inc');
?>
		<div id="footer">
			<p>&copy; 2007<?php $current_year = date('Y'); if( $current_year > 2007 ){ print( " - ".date('Y') ); } ?> <a href="https://cirrus.twiddles.com/">James Nash</a>.</p>
			<p>This site is a member of the <a href="https://www.twiddles.com/">Twiddles Network</a>.</p>
			<p class="gap">Nokia, N-Series, N76, S60 and all Nokia-based marks and logos are trade marks of Nokia Corporation. This website is not in any way endorsed or supported by Nokia Corporation.</p>
		</div>
	</body>
</html>