<?php

header('Content-type: application/atom+xml');


print('<?xml version="1.0" encoding="UTF-8"?>');

?><feed xmlns="http://www.w3.org/2005/Atom" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:opds="http://opds-spec.org/2010/catalog" xmlns:app="http://www.w3.org/2007/app" xmlns:at="http://purl.org/atompub/tombstones/1.0" xmlns:pp="http://pugpig.com/2014/atom/">
  <!-- Atom External Feed - Generated: Wed, 15 Apr 15 15:54:08 +0000 -->
  <!-- Generated by: Pugpig WordPress Plugin 2.1.0  (standalone 2.3.0) -->
  <!-- Status: publish. Number of editions to include: 10 -->
  <id>opds</id>
  <link type="application/atom+xml;profile=opds-catalog;kind=acquisition" href="http://event-horizon.cyberfinity.net/opds.php" rel="self"/>
  <author>
    <name>Pugpig</name>
  </author>
  <title>All Issues</title>
  <subtitle>Atom External Feed</subtitle>
  <updated>2015-03-03T11:43:11+00:00</updated>
  <entry>
    <title>in24</title>
    <id>editions_in24</id>
    <updated>2015-03-03T11:43:11+00:00</updated>
    <published>2015-03-02T01:00:00+00:00</published>
    <dcterms:issued>2015-03-02</dcterms:issued>
    <summary type="text"></summary>
    <link type="image/jpg" href="http://54.73.61.31/wp-content/uploads/2015/03/in24.png" rel="http://opds-spec.org/image"/>
    <!--Free edition-->
    <link type="application/atom+xml" href="http://54.73.61.31/editionfeed/347/pugpig_atom_contents.manifest" rel="http://opds-spec.org/acquisition"/>
    <link type="application/atom+xml" href="http://54.73.61.31/editionfeed/347/pugpig_atom_contents.manifest" rel="alternate"/>
  </entry>
  <entry>
    <title>Fedex</title>
    <id>editions_fedex</id>
    <updated>2015-03-02T13:59:16+00:00</updated>
    <published>2015-03-02T01:00:00+00:00</published>
    <dcterms:issued>2015-03-02</dcterms:issued>
    <summary type="text"></summary>
    <link type="image/jpg" href="/wp-content/uploads/2015/03/fed-ex.png" rel="http://opds-spec.org/image"/>
    <!--Free edition-->
    <link type="application/atom+xml" href="/editionfeed/269/pugpig_atom_contents.manifest" rel="http://opds-spec.org/acquisition"/>
    <link type="application/atom+xml" href="/editionfeed/269/pugpig_atom_contents.manifest" rel="alternate"/>
  </entry>
  <entry>
    <title>Bank White label concepts</title>
    <id>editions_wipro-test</id>
    <updated>2015-02-24T10:16:10+00:00</updated>
    <published>2015-02-23T01:00:00+00:00</published>
    <dcterms:issued>2015-02-23</dcterms:issued>
    <summary type="text"></summary>
    <link type="image/jpg" href="/wp-content/uploads/2015/02/white-label.png" rel="http://opds-spec.org/image"/>
    <!--Free edition-->
    <link type="application/atom+xml" href="/editionfeed/33/pugpig_atom_contents.manifest" rel="http://opds-spec.org/acquisition"/>
    <link type="application/atom+xml" href="/editionfeed/33/pugpig_atom_contents.manifest" rel="alternate"/>
  </entry>
  <entry>
    <title>Ophthalmologist Social Collaboration App: Android Prototype</title>
    <id>editions_wipro-novartis-rr-android</id>
    <updated>2015-02-27T11:52:08+00:00</updated>
    <published>2015-02-23T01:00:00+00:00</published>
    <dcterms:issued>2015-02-23</dcterms:issued>
    <summary type="text">Screenshots of Ophthalmologist Social Collaboration App: Android Prototype</summary>
    <link type="image/jpg" href="/wp-content/uploads/2015/02/RR-cover.jpg" rel="http://opds-spec.org/image"/>
    <!--Free edition-->
    <link type="application/atom+xml" href="/editionfeed/34/pugpig_atom_contents.manifest" rel="http://opds-spec.org/acquisition"/>
    <link type="application/atom+xml" href="/editionfeed/34/pugpig_atom_contents.manifest" rel="alternate"/>
  </entry>
</feed>
